testing with wget

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,15 +31,16 @@ jobs:
 
     - name: Wait for services to be ready
       run: |
-        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)
-        echo "$respone"
+        response=$(wget --server-response --spider http://localhost:8000/health 2>&1 | awk '/HTTP\// {print $2}' | tail -1)
+
         if [ "$response" == "200" ]; then
         echo "App is healthy!"
         exit 0
+        else
+        echo "Health check failed with status code: $response"
+        exit 1
         fi
-        echo "Waiting for app... ($i)"
-        sleep 3
-        echo "Health check failed"
+
         docker-compose logs
 
     - name: Shut down
